FROM ubuntu:latest
RUN apt-get update -y
RUN apt-get install -y python3-pip python-dev build-essential
COPY . .
RUN pip3 install -r requirements.txt
ENTRYPOINT ["uvicorn"]
CMD ["api:app", "--reload", "--host", "0.0.0.0"]